language: python

matrix:
    include:
        - os: linux
          sudo: required
        - os: osx

install:
  - bash ./installation_script.sh

script:
  python3 -c "import MWTracker; print(MWTracker.__version__)"
  python3 -c "import cv2; print(cv2.__version__)"

