language: generic
notifications:
  email: false

matrix:
    include:
        - os: linux
          sudo: required
        - os: osx
          osx_image: xcode7

install:
  - bash ./installation_script.sh

script:
  - which python3 
  - python3 ./installation/installation_test.py