language: generic

matrix:
    include:
        - os: linux
          sudo: required
        - os: osx
          osx_image: xcode6.4

install:
  - bash ./installation_script.sh

script:
  - which python3 
  - python3 -c "import MWTracker; print(MWTracker.__version__)"
  - python3 -c "import cv2; print(cv2.__version__)"