language: python
python: 
# We don't actually use the Travis Python, but this keeps it organized.
- "3.5"
- "3.6"

notifications:
  email: false

matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
        - os: linux
          sudo: required
        - os: osx
          osx_image: xcode7

install:
  # install anaconda
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  
  # create testing enviroment
  - conda config --add channels conda-forge 
  - conda create -q -n test-environment python=$TRAVIS_PYTHON 
    numpy matplotlib pytables pandas gitpython pyqt=5 
    h5py scipy scikit-learn scikit-image seaborn xlrd 
    cython statsmodels keras opencv
  - source activate test-environment
  - pip install tensorflow 
  
  # install tierpsy
  - bash installation/installation_script.sh --setup_modules
  
before_script:
  #download examples
  - installation/instalation_script.sh --download_examples

script:
  - which python3 
  - python tests/run_tests.py
