package:
  name: tierpsy
  version: "1.5.1"

source:
  path: "/Users/avelinojaver/Documents/GitHub/tierpsy-tracker"
  #git_rev: "v1.5.0"
  #git_url: "https://github.com/ver228/tierpsy-tracker"

build:
  entry_points:
    - tierpsy = tierpsy.gui.SelectApp:main
  osx_is_app: True

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - numpy >=1.14
    - setuptools
    - cython
    
  run:
    - python {{PY_VER}}*,>=3.6
    - numpy >=1.14
    - matplotlib 
    - pytables 
    - pandas 
    - pyqt
    - scipy 
    - scikit-learn 
    - scikit-image
    - statsmodels 
    - numba 
    - keras=2.1.5 
    - opencv 
    - tensorflow 

app:
  entry: tierpsy
  summary: Scientific Python Development Environment
  type: desk

test:
  # Python imports
  imports:
    - tierpsy
    - tierpsy.features.tierpsy_features
    - tierpsy.features.open_worm_analysis_toolbox

about:
  home: https://github.com/ver228/tierpsy-tracker
  license: MIT
  license_file: LICENSE
  summary: 'Tierpsy Tracker Multi-Worm Tracker'